# Generated by Django 5.0.dev20230405040931 on 2023-04-05 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('department_head_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('faculty_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.department')),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.department')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('roll_number', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.department')),
                ('facad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='enrollment',
            fields=[
                ('enrollment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField()),
                ('grade', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.course')),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.student')),
            ],
        ),
    ]
